# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87560829602f32ecb23b1eb03b618a9b8743cc3ba89581630b20afee8559ae67eab7f36235dada8b3163a6e0d4b2f23952d5c51d8dd203ed2e727a0084a79b2

test:
  secret_key_base: 062e7cf7d35a289fa95271a7a436c383db55a6f8e2eb65a2670efc520c921a4ecd0bc2093a174ddfe6044745b6f01ebb40d3ef835e379e4ca6c0e2b71037e10e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
